CREATE TABLE IF NOT EXISTS PRODUCT1 (
  PRO_ID TEXT PRIMARY KEY,
  PRO_NAME TEXT,
  PRO_PRICE REAL,
  PRO_COM TEXT
);

INSERT INTO PRODUCT1 (PRO_ID,PRO_NAME,PRO_PRICE,PRO_COM) VALUES
  ('101','MOTHERBOARD',600,'15'),
  ('102','MOUSE',650,'14'),
  ('103','KEYBOARD',2500,'13'),
  ('104','CAMERA',2000,'14');


SELECT * FROM PRODUCT1;
SELECT PRO_NAME, PRO_PRICE

FROM PRODUCT1

WHERE PRO_PRICE = (SELECT MIN(PRO_PRICE) FROM PRODUCT1);

SELECT PRO_NAME, PRO_PRICE

FROM PRODUCT1

WHERE PRO_PRICE = (SELECT MAX(PRO_PRICE) FROM PRODUCT1);

