CREATE TABLE IF NOT EXISTS DOCUMENT (
  EMPLOYEE_ID TEXT,
  NAME TEXT,
  DEPARTMENT_ID TEXT,
  MANAGER_ID TEXT,
  SALARY REAL 
);

INSERT INTO DOCUMENT (EMPLOYEE_ID,NAME,DEPARTMENT_ID,MANAGER_ID,SALARY) VALUES
  ('100','STEVEN KING','90','100',24000),
  ('101','NEENA KOCCHAR','90','100',17000),
  ('102','LEX DEHAAN','90','103',9000),
  ('103','BRUCE LEE','60','103',9000),
  ('104','DAWK','90','109',20000);
SELECT * FROM DOCUMENT;
SELECT DEPARTMENT_ID AS 'DEPARTMENT CODE',
COUNT(*) AS 'NO. OF EMPLOYEES'
FROM DOCUMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID,SUM(SALARY)

FROM DOCUMENT

GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS 'DEPARTMENT CODE',
COUNT(*) AS 'NO. OF EMPLOYEES',
SUM(SALARY) AS 'TOTAL SALARY'
FROM DOCUMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS 'DEPARTMENT CODE',

SUM(SALARY) AS 'TOTAL SALARY'
FROM DOCUMENT
WHERE MANAGER_ID = '103'
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, 
COUNT(*) AS 'NO. OF EMPLOYEES'

FROM DOCUMENT
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 2;




