CREATE TABLE HELLO(
  NAME TEXT,
  CLASS TEXT,
  SECTION TEXT
);
INSERT INTO HELLO(NAME,CLASS,SECTION) VALUES
  ('BHAGATH','9','A'),
  ('ARJUN','9','B'),
  ('DOHINI','9','A');

SELECT * FROM HELLO


SELECT * FROM HELLO WHERE SECTION='B' ;

