CREATE TABLE IF NOT EXISTS NOBLE_WIN (
  YEAR INTEGER,
  SUBJECT TEXT,
  WINNER TEXT,
  COUNTRY TEXT,
  CATEGORY TEXT
);

INSERT INTO NOBLE_WIN (YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY) VALUES
  (1970,'PHYSICS','HANNES ALFVEN','SWEDEN','SCIENTIST'),
  (1960,'PHYSICS','CV RAMAN','INDIA','SCIENTIST'),
  (1930,'MATHEMATICS','SRINIVASA RAMUNAJA','INDIA','MATHEMATICIAN'),
  (1975,'PHYSICS','PETER','CHILE','SCIENTIST'),
  (1975,'BIOLOGY','PHILIPS','USA','PRIME MINISTER'),
  (1970,'PHYSICS','LOUIS NEEL','FRANCE','SCIENTIST'),
  (1971,'PHYSICS','PAUL','FRANCE','SCIENTIST'),
  (1971,'CHEMISTRY','HAMILTON','SWEDEN','LINGUIST'),
  (1972,'ECONIMICE','JOSEPH','RUSSIA','ECONOMIST');

SELECT * FROM NOBLE_WIN;
SELECT * FROM NOBLE_WIN
WHERE SUBJECT NOT LIKE '%P';

SELECT * FROM NOBLE_WIN
ORDER BY WINNER ASC;




